### ISSUE TITLE
CannotResolveClassException when starting JMeter with the Simulap plugin

### ISSUE THREAD

**Issue by etekes** [SIMULAP/simulap-plugin-sip#26]
## Description
I'm getting the Exception (file with stacktrace attached & excerpt posted below) when I start JMeter with the Simulap plugin as per the instructions in the Readme. 

Excerpt: 

```
2020-05-14 14:24:21,969 ERROR o.a.j.JMeter: Failure loading test file
java.lang.IllegalArgumentException: Problem loading XML from:'C:\Users\userX\Documents\Tools\simulap-plugin-sip-master\tests\SIPtestsGlobal.jmx'. 
Cause:
CannotResolveClassException: org.apache.jmeter.protocol.sip.config.SipNodeElement

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/org.apache.jmeter.protocol.sip.config.SipNodeElement
line number         : 208
version             : 5.2.1
-------------------------------
	at org.apache.jmeter.save.SaveService.readTree(SaveService.java:459) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:432) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.JMeter.startGui(JMeter.java:411) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.JMeter.start(JMeter.java:545) [ApacheJMeter_core.jar:5.2.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.apache.jmeter.NewDriver.main(NewDriver.java:253) [ApacheJMeter.jar:5.2.1]
Caused by: com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/org.apache.jmeter.protocol.sip.config.SipNodeElement
line number         : 208
version             : 5.2.1
-------------------------------
```

## Motivation and Context

* JMeter version: 5.2.1
* Plugin version: 19.04
* Operating System version: Windows 10 Pro

## Steps to reproduce the problem (if appropriate)

Starting JMeter with the command `mvn -X install -Djmeter.command=JMETER_HOME/bin/jmeter`

## Resources
[simulapException.txt](https://github.com/SIMULAP/simulap-plugin-sip/files/4628361/simulapException.txt)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I give my issue a label.
- [ ] I put my issue into `Support` project.
- [ ] I provide the required resources.

**Comment by Pancor** [comment]
I managed to fix the problem. First of all you will have to edit file SIPtestsGlobal.jmx that is placed in simulap-plugin-sip/tests and replace all text occurens from org.apache.jmeter to com.hpe.simulap,, there is something like 1,2k of changes to be made in this file, Then you will also have to place this library:
https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api/2.2.9
in $JMETER_HOME/lib. After this changes it should work.

**Comment by vherilier** [comment]
Please insert into JMeter's `bin/upgrade.properties` file the content of `bin/upgrade.properties.sip` to solves the issue

**Comment by f-helm** [comment]
Had some issues getting it to run, but this finally worked for me:
- As @Pancor said, replace all occurrences of `org.apache.jmeter` with `com.hpe.simulap` in `simulap-plugin-sip/tests/SIPtestsGlobal.jmx`
- Make sure to use Java 8
- Copy [JAXB API jar file](https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api/2.2.9) into JMETER_HOME/libexec/lib/ directory (using jMeter 5.4.3)

**Comment by f-helm** [comment]
> Please insert into JMeter's `bin/upgrade.properties` file, the content of `bin/upgrade.properties.sip` to solves the issue.

This didn't work for me, I had to manually replace names in the test plan file.
